name: outout
on: push
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
     - name: print the message
       run: echo "hello everyone" >> $GITHUB_OUTPUT
     - name: print the same
       run: echo "$GITHUB_OUTPUT"
